language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"

matrix:
  include:
    - python: "3.7"
      dist: "xenial"
      sudo: true
install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  coverage run setup.py test

after_success:
  coveralls
