language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5.0b3"
  - "3.5-dev"
  - "nightly"
  - "pypy"
  - "pypy3"

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  coverage run setup.py test

after_success:
  coveralls
